// <auto-generated />
using System;
using BlueMoon.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueMoon.Migrations
{
    [DbContext(typeof(MySqlDataBaseContext))]
    [Migration("20251113123339_Migration_0.0.0.10")]
    partial class Migration_00010
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlueMoon.Entities.Models.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ProdutoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("produto_codigo");

                    b.Property<string>("ProdutoMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("produto_marca");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("produto_nome");

                    b.Property<decimal>("ProdutoValorVenda")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("produto_valor_venda");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("id_produto")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_produto");

                    b.Property<Guid>("id_venda")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_venda");

                    b.HasKey("Id");

                    b.HasIndex("id_produto");

                    b.HasIndex("id_venda");

                    b.ToTable("ItemVendas");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cidade");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("telefone");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<decimal>("MargemLucro")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("margem_lucro");

                    b.Property<string>("NCM")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("ncm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_estoque");

                    b.Property<int>("QuantidadeEstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_estoque_minimo");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("valor_custo");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("valor_venda");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Admissao")
                        .HasColumnType("date")
                        .HasColumnName("admissao");

                    b.Property<int>("Cargo")
                        .HasColumnType("int")
                        .HasColumnName("cargo");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<TimeOnly>("HorarioFimCargaHoraria")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario_fim_carga_horaria");

                    b.Property<TimeOnly>("HorarioInicioCargaHoraria")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario_inicio_carga_horaria");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("login");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("salario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("senha");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<Guid>("id_pessoa")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_pessoa");

                    b.HasKey("Id");

                    b.HasIndex("id_pessoa");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime>("DataFaturamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_faturamento");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("valor_total");

                    b.Property<Guid>("id_pessoa")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_pessoa");

                    b.Property<Guid>("id_usuario")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("id_pessoa");

                    b.HasIndex("id_usuario");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.ItemVenda", b =>
                {
                    b.HasOne("BlueMoon.Entities.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueMoon.Entities.Models.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("id_venda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Usuario", b =>
                {
                    b.HasOne("BlueMoon.Entities.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("id_pessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Venda", b =>
                {
                    b.HasOne("BlueMoon.Entities.Models.Pessoa", "Cliente")
                        .WithMany()
                        .HasForeignKey("id_pessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueMoon.Entities.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("BlueMoon.Entities.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
